In [1]:
import numpy as np

y_predicted=np.array([1,1,0,0,1])
y_true=([0.30,0.7,1,0,0.5])

In [10]:
def mae(y_true,y_predicted):
    total_error=0
    for yt ,yp in zip(y_true,y_predicted):
        total_error+= abs(yt-yp)
    print("Total error: ",total_error)
    mae=total_error/len(y_true)
    print("Mean Absolute Error: ",mae)
    return mae

mar(y_true,y_predicted)

In [11]:
mae(y_true,y_predicted)

Total error:  2.5
Mean Absolute Error:  0.5


0.5

In [13]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [15]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [18]:
np.log([0.0000000000000000001])

array([-43.74911677])

In [19]:
eplison=1e-15

In [22]:
y_predicted_new=[max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [23]:
y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [25]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [26]:
y_p=np.array([1,1,0,0,1])
y_t=np.array([0.30,0.7,1,0,0.5])

In [27]:
def mse(y_t,y_p):
    total_error=0
    for yt,yp in zip(y_t,y_p):
        total_error+=(yt-yp)**2
    print("total squared error: ",total_error)
    mse=total_error/len(y_true)
    print("MSE is ",mse)
    return mse

In [28]:
mse(y_t,y_p)

total squared error:  1.83
MSE is  0.366


0.366

In [29]:
np.mean(np.square(y_t-y_p))

0.366